### PR TITLE
UI changes

### PR DESCRIPTION
**Pull request by Benjorbious**
creating and constraining slang, translate, and the continue buttons using XML.

### CODE REVIEW

**Review by shazz-sultan — APPROVED** [review]
I don't know xml but it looks good

**Comment by Benjorbious** [comment]
Screenshot 2023-09-26 190248

**Comment by Benjorbious** [comment]
here's the landscape version.

Screenshot 2023-09-26 190619

**Review by donnelldebnam — APPROVED** [review]
LGTM!

**Pull request merged**
